
//list of words to guess.
exports.newWord = {
  wordList: ['PHILIP J FRY', 'LILA', 'PROFESSOR', 'AMY WONG', 'BENDER BENDING RODRIGUEZ', 'HERMES CONRAD', 'DOCTOR JOHN ZOIDBERG', 'ZAPP BRANNIGAN', 'KIF KROKER', 'HYPNOTOAD', 'MOM', 'LORD NIBBLER' ]
};





